const { getPool } = require("./postgres");

let escalasConfigColumnPromise = null;
let pontoLocationColumnsPromise = null;
let locaisPermitidosPromise = null;
let configuracoesPromise = null;

function resetPromiseOnFailure(promise, reset) {
  promise.catch(() => {
    reset();
  });
  return promise;
}

async function runEnsureEscalasConfigColumn() {
  const pool = await getPool();
  await pool.request().query(`
    ALTER TABLE app_escalas ADD COLUMN IF NOT EXISTS configuracao_json text NULL
  `);
}

function ensureEscalasConfigColumn() {
  if (!escalasConfigColumnPromise) {
    escalasConfigColumnPromise = resetPromiseOnFailure(
      runEnsureEscalasConfigColumn(),
      () => {
        escalasConfigColumnPromise = null;
      }
    );
  }

  return escalasConfigColumnPromise;
}

async function runEnsurePontoLocationColumns() {
  const pool = await getPool();
  await pool.request().query(`
    ALTER TABLE app_ponto_registros
      ADD COLUMN IF NOT EXISTS latitude numeric(10, 7) NULL,
      ADD COLUMN IF NOT EXISTS longitude numeric(10, 7) NULL,
      ADD COLUMN IF NOT EXISTS accuracy_meters numeric(10, 2) NULL,
      ADD COLUMN IF NOT EXISTS location_captured_at timestamp(0) NULL
  `);
}

function ensurePontoLocationColumns() {
  if (!pontoLocationColumnsPromise) {
    pontoLocationColumnsPromise = resetPromiseOnFailure(
      runEnsurePontoLocationColumns(),
      () => {
        pontoLocationColumnsPromise = null;
      }
    );
  }

  return pontoLocationColumnsPromise;
}

async function runEnsureLocaisPermitidosSchema() {
  const pool = await getPool();
  await pool.request().query(`
    CREATE TABLE IF NOT EXISTS app_ponto_locais_permitidos (
      id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      nome varchar(120) NOT NULL,
      latitude numeric(10, 7) NOT NULL,
      longitude numeric(10, 7) NOT NULL,
      raio_metros integer NOT NULL DEFAULT 100,
      ativo boolean NOT NULL DEFAULT true,
      created_at timestamp(0) NOT NULL DEFAULT now(),
      updated_at timestamp(0) NULL
    );

    CREATE INDEX IF NOT EXISTS ix_app_ponto_locais_permitidos_ativo
      ON app_ponto_locais_permitidos (ativo);
  `);
}

function ensureLocaisPermitidosSchema() {
  if (!locaisPermitidosPromise) {
    locaisPermitidosPromise = resetPromiseOnFailure(
      runEnsureLocaisPermitidosSchema(),
      () => {
        locaisPermitidosPromise = null;
      }
    );
  }

  return locaisPermitidosPromise;
}

async function runEnsureConfiguracoesSchema() {
  const pool = await getPool();
  await pool.request().query(`
    CREATE TABLE IF NOT EXISTS app_configuracoes (
      chave varchar(80) PRIMARY KEY,
      valor text NOT NULL,
      updated_at timestamp(0) NOT NULL DEFAULT now()
    );

    INSERT INTO app_configuracoes (chave, valor)
    VALUES ('validacao_localizacao_ativa', 'false')
    ON CONFLICT (chave) DO NOTHING;
  `);
}

function ensureConfiguracoesSchema() {
  if (!configuracoesPromise) {
    configuracoesPromise = resetPromiseOnFailure(
      runEnsureConfiguracoesSchema(),
      () => {
        configuracoesPromise = null;
      }
    );
  }

  return configuracoesPromise;
}

module.exports = {
  ensureConfiguracoesSchema,
  ensureEscalasConfigColumn,
  ensureLocaisPermitidosSchema,
  ensurePontoLocationColumns,
};
