-- Execute este arquivo no SQL Editor do Supabase antes de subir o backend.
-- O projeto usa nomes de colunas de Usuarios com maiusculas para preservar a API existente.

CREATE TABLE IF NOT EXISTS "Usuarios" (
  "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Matricula" varchar(30) NOT NULL UNIQUE,
  "Senha" varchar(255) NOT NULL,
  "Nome" varchar(120) NOT NULL,
  "Perfil" varchar(30) NOT NULL DEFAULT 'funcionario',
  "Ativo" boolean NOT NULL DEFAULT true,
  "CriadoEm" timestamp(0) NOT NULL DEFAULT now(),
  "AtualizadoEm" timestamp(0) NULL,
  "LojaId" integer NULL,
  "SetorId" integer NULL,
  "EscalaId" integer NULL,
  "DataInicioPonto" date NULL
);

CREATE TABLE IF NOT EXISTS app_lojas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo integer NOT NULL UNIQUE,
  nome varchar(150) NOT NULL,
  cidade varchar(100) NOT NULL,
  bairro varchar(100) NULL,
  cnpj varchar(20) NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamp(0) NOT NULL DEFAULT now(),
  updated_at timestamp(0) NULL
);

CREATE TABLE IF NOT EXISTS app_escalas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome varchar(150) NOT NULL,
  tipo varchar(30) NOT NULL DEFAULT 'fixa',
  ativo boolean NOT NULL DEFAULT true,
  configuracao_json text NULL,
  created_at timestamp(0) NOT NULL DEFAULT now(),
  updated_at timestamp(0) NULL
);

CREATE TABLE IF NOT EXISTS app_escala_dias (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  escala_id integer NOT NULL REFERENCES app_escalas(id) ON DELETE CASCADE,
  dia_semana smallint NOT NULL CHECK (dia_semana BETWEEN 1 AND 7),
  meta_minutos integer NOT NULL DEFAULT 0,
  ativo boolean NOT NULL DEFAULT true,
  CONSTRAINT ux_app_escala_dias_escala_dia UNIQUE (escala_id, dia_semana)
);

CREATE TABLE IF NOT EXISTS app_funcionario_escalas (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula varchar(30) NOT NULL,
  escala_id integer NULL REFERENCES app_escalas(id),
  data_inicio date NOT NULL,
  created_at timestamp(0) NOT NULL DEFAULT now(),
  updated_at timestamp(0) NOT NULL DEFAULT now(),
  CONSTRAINT ux_app_funcionario_escalas_matricula_data UNIQUE (matricula, data_inicio)
);

CREATE TABLE IF NOT EXISTS app_funcionario_auditoria (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funcionario_id integer NOT NULL,
  matricula varchar(30) NOT NULL,
  campo varchar(80) NOT NULL,
  valor_anterior varchar(255) NULL,
  valor_novo varchar(255) NULL,
  alterado_por_matricula varchar(30) NULL,
  alterado_por_nome varchar(120) NULL,
  alterado_em timestamp(0) NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS app_ponto_registros (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricula varchar(20) NOT NULL,
  data_ponto date NOT NULL,
  hora_ponto time(0) NOT NULL,
  data_hora timestamp(0) NOT NULL DEFAULT (now() AT TIME ZONE 'America/Sao_Paulo'),
  tipo varchar(20) NOT NULL,
  created_at timestamp(0) NOT NULL DEFAULT now(),
  CONSTRAINT ck_app_ponto_registros_tipo CHECK (tipo IN ('entrada1', 'saida1', 'entrada2', 'saida2'))
);

CREATE TABLE IF NOT EXISTS app_feriados (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_feriado date NOT NULL,
  descricao varchar(150) NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_at timestamp(0) NOT NULL DEFAULT now(),
  updated_at timestamp(0) NULL
);

CREATE TABLE IF NOT EXISTS app_ponto_ajustes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  funcionario_id integer NOT NULL,
  matricula varchar(20) NOT NULL,
  data_ponto date NOT NULL,
  entrada1 time(0) NULL,
  saida1 time(0) NULL,
  entrada2 time(0) NULL,
  saida2 time(0) NULL,
  tipo_ajuste varchar(40) NOT NULL,
  meta_minutos_override integer NULL,
  motivo varchar(200) NOT NULL,
  observacao varchar(500) NULL,
  ativo boolean NOT NULL DEFAULT true,
  created_by varchar(120) NULL,
  created_at timestamp(0) NOT NULL DEFAULT now(),
  updated_at timestamp(0) NULL,
  CONSTRAINT ck_app_ponto_ajustes_tipo CHECK (
    tipo_ajuste IN (
      'ALTERAR_BATIDA',
      'JUSTIFICAR_FALTA',
      'ABONAR_DIA',
      'FALTA_DESCONTADA',
      'PAGO_EM_FOLHA',
      'MARCAR_FERIADO',
      'MARCAR_FOLGA',
      'MARCAR_TRABALHO'
    )
  )
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuarios_loja'
  ) THEN
    ALTER TABLE "Usuarios"
      ADD CONSTRAINT fk_usuarios_loja
      FOREIGN KEY ("LojaId") REFERENCES app_lojas(id)
      DEFERRABLE INITIALLY IMMEDIATE;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'fk_usuarios_escala'
  ) THEN
    ALTER TABLE "Usuarios"
      ADD CONSTRAINT fk_usuarios_escala
      FOREIGN KEY ("EscalaId") REFERENCES app_escalas(id)
      DEFERRABLE INITIALLY IMMEDIATE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_app_ponto_registros_matricula_data
  ON app_ponto_registros (matricula, data_ponto);

CREATE INDEX IF NOT EXISTS ix_app_ponto_registros_matricula_hora
  ON app_ponto_registros (matricula, data_hora DESC);

CREATE UNIQUE INDEX IF NOT EXISTS ux_app_feriados_data
  ON app_feriados (data_feriado);

CREATE INDEX IF NOT EXISTS ix_app_ponto_ajustes_funcionario_data_ativo
  ON app_ponto_ajustes (funcionario_id, data_ponto, ativo);

CREATE INDEX IF NOT EXISTS ix_app_funcionario_auditoria_funcionario
  ON app_funcionario_auditoria (funcionario_id, alterado_em DESC);

INSERT INTO "Usuarios" ("Matricula", "Senha", "Nome", "Perfil", "Ativo")
VALUES
  ('1001', '123456', 'Funcionario Teste', 'funcionario', true),
  ('1002', '123456', 'Administrador', 'admin', true)
ON CONFLICT ("Matricula") DO NOTHING;
